/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.edu.cesba;

/**
 *
 * @author HP
 */
public class DemoCal extends javax.swing.JFrame {
    float num1;
    float num2;
    float res;
    String signo;
    

    /**
     * Creates new form DemoCal
     */
    public DemoCal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta_1 = new javax.swing.JLabel();
        txt_output = new javax.swing.JLabel();
        btn_Clear = new javax.swing.JButton();
        btn_X = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_Div = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_Mas = new javax.swing.JButton();
        btn_Igual = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        Btn_porcentaje = new javax.swing.JButton();
        btn_retoceso = new javax.swing.JButton();
        btn_pi = new javax.swing.JButton();
        btn_cuadrado = new javax.swing.JButton();
        btn_raiz = new javax.swing.JButton();
        btn_cubica = new javax.swing.JButton();
        btn_sen = new javax.swing.JButton();
        btn_cos = new javax.swing.JButton();
        btn_tan = new javax.swing.JButton();
        btn_fac = new javax.swing.JButton();
        btn_log = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        etiqueta_1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        etiqueta_1.setForeground(new java.awt.Color(204, 51, 255));
        etiqueta_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_1.setText("CALCULADORA CESBA");

        txt_output.setBackground(new java.awt.Color(0, 0, 0));
        txt_output.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txt_output.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resultado:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 12))); // NOI18N

        btn_Clear.setBackground(new java.awt.Color(51, 51, 51));
        btn_Clear.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(51, 255, 204));
        btn_Clear.setText("C");
        btn_Clear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_X.setBackground(new java.awt.Color(51, 51, 51));
        btn_X.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_X.setForeground(new java.awt.Color(51, 255, 204));
        btn_X.setText("X");
        btn_X.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(51, 51, 51));
        btn_menos.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_menos.setForeground(new java.awt.Color(51, 255, 204));
        btn_menos.setText("-");
        btn_menos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_Div.setBackground(new java.awt.Color(51, 51, 51));
        btn_Div.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Div.setForeground(new java.awt.Color(51, 255, 204));
        btn_Div.setText("/");
        btn_Div.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Div.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(51, 51, 51));
        btn_1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_1.setForeground(new java.awt.Color(51, 255, 204));
        btn_1.setText("1");
        btn_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(51, 51, 51));
        btn_4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_4.setForeground(new java.awt.Color(51, 255, 204));
        btn_4.setText("4");
        btn_4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(51, 51, 51));
        btn_7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_7.setForeground(new java.awt.Color(51, 255, 204));
        btn_7.setText("7");
        btn_7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(51, 51, 51));
        btn_0.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_0.setForeground(new java.awt.Color(51, 255, 204));
        btn_0.setText("0");
        btn_0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(51, 51, 51));
        btn_2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_2.setForeground(new java.awt.Color(51, 255, 204));
        btn_2.setText("2");
        btn_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(51, 51, 51));
        btn_5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_5.setForeground(new java.awt.Color(51, 255, 204));
        btn_5.setText("5");
        btn_5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(51, 51, 51));
        btn_8.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_8.setForeground(new java.awt.Color(51, 255, 204));
        btn_8.setText("8");
        btn_8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(51, 51, 51));
        btn_3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_3.setForeground(new java.awt.Color(51, 255, 204));
        btn_3.setText("3");
        btn_3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(51, 51, 51));
        btn_6.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_6.setForeground(new java.awt.Color(51, 255, 204));
        btn_6.setText("6");
        btn_6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(51, 51, 51));
        btn_9.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_9.setForeground(new java.awt.Color(51, 255, 204));
        btn_9.setText("9");
        btn_9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_Mas.setBackground(new java.awt.Color(51, 51, 51));
        btn_Mas.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Mas.setForeground(new java.awt.Color(51, 255, 204));
        btn_Mas.setText("+");
        btn_Mas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Mas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasActionPerformed(evt);
            }
        });

        btn_Igual.setBackground(new java.awt.Color(51, 51, 51));
        btn_Igual.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Igual.setForeground(new java.awt.Color(51, 255, 204));
        btn_Igual.setText("=");
        btn_Igual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_Igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IgualActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(51, 51, 51));
        btn_punto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(51, 255, 204));
        btn_punto.setText(".");
        btn_punto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        Btn_porcentaje.setBackground(new java.awt.Color(51, 51, 51));
        Btn_porcentaje.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        Btn_porcentaje.setForeground(new java.awt.Color(51, 255, 204));
        Btn_porcentaje.setText("%");
        Btn_porcentaje.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_porcentajeActionPerformed(evt);
            }
        });

        btn_retoceso.setBackground(new java.awt.Color(51, 51, 51));
        btn_retoceso.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_retoceso.setForeground(new java.awt.Color(51, 255, 204));
        btn_retoceso.setText("Borrar");
        btn_retoceso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_retoceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retocesoActionPerformed(evt);
            }
        });

        btn_pi.setBackground(new java.awt.Color(51, 51, 51));
        btn_pi.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_pi.setForeground(new java.awt.Color(51, 255, 204));
        btn_pi.setText("Pi");
        btn_pi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_piActionPerformed(evt);
            }
        });

        btn_cuadrado.setBackground(new java.awt.Color(51, 51, 51));
        btn_cuadrado.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_cuadrado.setForeground(new java.awt.Color(51, 255, 204));
        btn_cuadrado.setText("x²");
        btn_cuadrado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuadradoActionPerformed(evt);
            }
        });

        btn_raiz.setBackground(new java.awt.Color(51, 51, 51));
        btn_raiz.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_raiz.setForeground(new java.awt.Color(51, 255, 204));
        btn_raiz.setText("2 √ ");
        btn_raiz.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_raizActionPerformed(evt);
            }
        });

        btn_cubica.setBackground(new java.awt.Color(51, 51, 51));
        btn_cubica.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_cubica.setForeground(new java.awt.Color(51, 255, 204));
        btn_cubica.setText("3 √ ");
        btn_cubica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cubicaActionPerformed(evt);
            }
        });

        btn_sen.setBackground(new java.awt.Color(51, 51, 51));
        btn_sen.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_sen.setForeground(new java.awt.Color(51, 255, 204));
        btn_sen.setText("Sen");
        btn_sen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_sen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_senActionPerformed(evt);
            }
        });

        btn_cos.setBackground(new java.awt.Color(51, 51, 51));
        btn_cos.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_cos.setForeground(new java.awt.Color(51, 255, 204));
        btn_cos.setText("Cos");
        btn_cos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosActionPerformed(evt);
            }
        });

        btn_tan.setBackground(new java.awt.Color(51, 51, 51));
        btn_tan.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_tan.setForeground(new java.awt.Color(51, 255, 204));
        btn_tan.setText("Tan");
        btn_tan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tanActionPerformed(evt);
            }
        });

        btn_fac.setBackground(new java.awt.Color(51, 51, 51));
        btn_fac.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_fac.setForeground(new java.awt.Color(51, 255, 204));
        btn_fac.setText("x!");
        btn_fac.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_fac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facActionPerformed(evt);
            }
        });

        btn_log.setBackground(new java.awt.Color(51, 51, 51));
        btn_log.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_log.setForeground(new java.awt.Color(51, 255, 204));
        btn_log.setText("Log10");
        btn_log.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btn_0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(btn_punto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                                            .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Btn_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_cubica, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_cos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_log, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_retoceso, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Mas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_Div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_X, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(etiqueta_1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_sen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_Div, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_retoceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_X, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_raiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(btn_cos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cubica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_fac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Mas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_output.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_DivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivActionPerformed
num1 = Float.parseFloat(txt_output.getText());
signo = "/";
txt_output.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DivActionPerformed

    private void btn_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XActionPerformed
num1 = Float.parseFloat(txt_output.getText());
signo = "*";
txt_output.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_XActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
txt_output.setText(txt_output.getText()+"1");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
txt_output.setText(txt_output.getText()+"2");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasActionPerformed
num1 = Float.parseFloat(txt_output.getText());
signo = "+";
txt_output.setText(" ");
// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MasActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
txt_output.setText(txt_output.getText()+"7");         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
txt_output.setText(txt_output.getText()+"0");      // TODO add your handling code here:
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
txt_output.setText(txt_output.getText()+"3");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
txt_output.setText(txt_output.getText()+"4");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
txt_output.setText(txt_output.getText()+"5");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
txt_output.setText(txt_output.getText()+"6");         // TODO add your handling code here:
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
txt_output.setText(txt_output.getText()+"8");         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
txt_output.setText(txt_output.getText()+"9");         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
txt_output.setText(txt_output.getText()+".");         // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
num1 = Float.parseFloat(txt_output.getText());
signo = "-";
txt_output.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IgualActionPerformed
 num2 = Float.parseFloat(txt_output.getText());
 switch(signo){
     case "+":
             txt_output.setText(Float.toString(num1 + num2));
         break;
         
    case "-":
             txt_output.setText(Float.toString(num1 - num2));
          break;   
    case "*":
             txt_output.setText(Float.toString(num1 * num2));
          break;
    case "/":
             txt_output.setText(Float.toString(num1 / num2));             
          break;  
          
    case "%":
        num1=num1;
        txt_output.setText(Float.toString(num1*num2/100));
        
 }
    }//GEN-LAST:event_btn_IgualActionPerformed

    private void Btn_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_porcentajeActionPerformed
       num1=Float.parseFloat(txt_output.getText());
       signo= "%";
       txt_output.setText(" ");
       
    }//GEN-LAST:event_Btn_porcentajeActionPerformed

    private void btn_retocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retocesoActionPerformed
 String currentText = txt_output.getText();
    if (!currentText.isEmpty()) {
        String newText = currentText.substring(0, currentText.length() - 1);
        txt_output.setText(newText);
    }    }//GEN-LAST:event_btn_retocesoActionPerformed

    private void btn_piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_piActionPerformed
    txt_output.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_btn_piActionPerformed

    private void btn_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuadradoActionPerformed
        float numero = Float.parseFloat(txt_output.getText());
    
    float cuadrado = numero * numero;
    
    txt_output.setText(String.valueOf(cuadrado));
    }//GEN-LAST:event_btn_cuadradoActionPerformed

    private void btn_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_raizActionPerformed
float numero = Float.parseFloat(txt_output.getText());
    float raiz = (float) Math.sqrt(numero);
    txt_output.setText(String.valueOf(raiz));    }//GEN-LAST:event_btn_raizActionPerformed

    private void btn_cubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cubicaActionPerformed
 float num = Float.parseFloat(txt_output.getText());

    float resultado = (float) Math.cbrt(num);

    txt_output.setText(String.valueOf(resultado));    }//GEN-LAST:event_btn_cubicaActionPerformed

    private void btn_cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosActionPerformed
  float num = Float.parseFloat(txt_output.getText());

    // Calcular el coseno del número
    double resultado = Math.cos(num);

    // Mostrar el resultado en el campo de texto
    txt_output.setText(String.valueOf(resultado));    }//GEN-LAST:event_btn_cosActionPerformed

    private void btn_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tanActionPerformed
 float num = Float.parseFloat(txt_output.getText());

    // Calcular la tangente del número
    double resultado = Math.tan(num);

    // Mostrar el resultado en el campo de texto
    txt_output.setText(String.valueOf(resultado));    }//GEN-LAST:event_btn_tanActionPerformed

    private void btn_senActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_senActionPerformed
 float num = Float.parseFloat(txt_output.getText());

    // Calcular el seno del número
    double resultado = Math.sin(num);

    // Mostrar el resultado en el campo de texto
    txt_output.setText(String.valueOf(resultado));    }//GEN-LAST:event_btn_senActionPerformed

    private void btn_facActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facActionPerformed
       // Obtener el número actualmente mostrado en la calculadora
    int num = Integer.parseInt(txt_output.getText());

    // Calcular el factorial del número
    int resultado = factorial(num);

    // Mostrar el resultado en el campo de texto
    txt_output.setText(String.valueOf(resultado));
} 

// Método para calcular el factorial de un número
private int factorial(int n) {
    if (n == 0 || n == 1) {
        return 1;
    } else {
        return n * factorial(n - 1);
    }
    }//GEN-LAST:event_btn_facActionPerformed

    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
   float num = Float.parseFloat(txt_output.getText());
    
    // Calcular el logaritmo en base 10 del número
    float resultado = (float) Math.log10(num);
    
    // Mostrar el resultado en el campo de texto
    txt_output.setText(String.valueOf(resultado));    }//GEN-LAST:event_btn_logActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoCal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoCal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_porcentaje;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Div;
    private javax.swing.JButton btn_Igual;
    private javax.swing.JButton btn_Mas;
    private javax.swing.JButton btn_X;
    private javax.swing.JButton btn_cos;
    private javax.swing.JButton btn_cuadrado;
    private javax.swing.JButton btn_cubica;
    private javax.swing.JButton btn_fac;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_pi;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_raiz;
    private javax.swing.JButton btn_retoceso;
    private javax.swing.JButton btn_sen;
    private javax.swing.JButton btn_tan;
    private javax.swing.JLabel etiqueta_1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_output;
    // End of variables declaration//GEN-END:variables
}
